version: "3"
services:
    nginx:
        image: nginx:1.9
        container_name: nginx1.9
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
            - ./nginx/etc/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/etc/certs:/etc/nginx/ssl
        ports:
            - 443:443
        environment:
            - NGINX_HOST=magento2.docker
#            - NGINX_PORT=80
    php:
        build:
            context: ./php7.4-fpm
        container_name: php7.4-fpm
        working_dir: /var/www/html
        volumes:
            - ./src:/var/www/html
        ports:
            - 9000
    db:
        image: mysql:8.0
        container_name: mysql8.0
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "Pwd123"
        ports:
            - 3306:3306
        expose:
            - 3306
    elasticsearch:
        image: elasticsearch:7.9.0
        container_name: elasticsearch7.9.0
        environment:
            discovery.type: single-node
            ELASTIC_USERNAME: "elastic"
            ELASTIC_PASSWORD: "Pwd123"
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200